FavouriteBoxers/Models/Boxer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FavouriteBoxers.Models
{
    public class Boxer
    {
        public int Id { get; set; }

        [Display(Name = "Full Name")]
        public string Full_Name { get; set; }

        public string Alias { get; set; }

        public string Nationality { get; set; }

        public string Stance { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "D.O.B")]
        public DateTime DOB { get; set; }

        public int setAge(DateTime dob)
        {
            int age = 0;
            age = DateTime.Now.Year - dob.Year;
            if (DateTime.Now.DayOfYear < dob.DayOfYear)
                age = age - 1;

            return age;
        }

        public Boxer()
        {
        }
    }
}

FavouriteBoxers/Models/ErrorViewModel.cs
namespace FavouriteBoxers.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FavouriteBoxers/Controllers/BoxerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavouriteBoxers.Data;
using FavouriteBoxers.Models;
using Microsoft.AspNetCore.Authorization;

namespace FavouriteBoxers.Controllers
{
    public class BoxerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BoxerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Boxer
        public async Task<IActionResult> Index()
        {
            return _context.Boxer != null ?
                        View(await _context.Boxer.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Boxer'  is null.");
        }


        // GET: Boxer/ShowSearchForm 
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST: Boxer/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            var boxer = await _context.Boxer.Where(boxer => boxer.Full_Name.ToLower().Contains(SearchPhrase.ToLower())).ToListAsync();

            Console.WriteLine("The searched boxer " + SearchPhrase + " " + boxer);

            return View("Index", boxer);
        }

        // GET: Boxer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Boxer == null)
            {
                return NotFound();
            }

            var boxer = await _context.Boxer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boxer == null)
            {
                return NotFound();
            }

            return View(boxer);
        }

        // GET: Boxer/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boxer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Full_Name,Alias,Nationality,Stance,DOB")] Boxer boxer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boxer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boxer);
        }

        // GET: Boxer/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Boxer == null)
            {
                return NotFound();
            }

            var boxer = await _context.Boxer.FindAsync(id);
            if (boxer == null)
            {
                return NotFound();
            }
            return View(boxer);
        }

        // POST: Boxer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Full_Name,Alias,Nationality,Stance,DOB")] Boxer boxer)
        {
            if (id != boxer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boxer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoxerExists(boxer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boxer);
        }

        // GET: Boxer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Boxer == null)
            {
                return NotFound();
            }

            var boxer = await _context.Boxer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boxer == null)
            {
                return NotFound();
            }

            return View(boxer);
        }

        // POST: Boxer/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Boxer == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Boxer'  is null.");
            }
            var boxer = await _context.Boxer.FindAsync(id);
            if (boxer != null)
            {
                _context.Boxer.Remove(boxer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoxerExists(int id)
        {
            return (_context.Boxer?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FavouriteBoxers/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FavouriteBoxers.Models;

namespace FavouriteBoxers.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FavouriteBoxers/Views/Boxer/Create.cshtml
@model FavouriteBoxers.Models.Boxer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Boxer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Full_Name" class="control-label"></label>
                <input asp-for="Full_Name" class="form-control" />
                <span asp-validation-for="Full_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stance" class="control-label"></label>
                <input asp-for="Stance" class="form-control" />
                <span asp-validation-for="Stance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FavouriteBoxers/Views/Boxer/Delete.cshtml
@model FavouriteBoxers.Models.Boxer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this boxer?</h3>
<div>
    <h4>Boxer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Full_Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Stance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stance)
        </dd>
        <dt class="col-sm-2">
            Age
        </dt>
        <dd class="col-sm-10">
            @Model.setAge(Model.DOB)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <p></p>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FavouriteBoxers/Views/Boxer/Details.cshtml
@model FavouriteBoxers.Models.Boxer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Boxer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Full_Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Stance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stance)
        </dd>
        <dt class="col-sm-2">
            Age
        </dt>
        <dd class="col-sm-10">
            @Model.setAge(Model.DOB)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FavouriteBoxers/Views/Boxer/Edit.cshtml
@model FavouriteBoxers.Models.Boxer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Boxer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Full_Name" class="control-label"></label>
                <input asp-for="Full_Name" class="form-control" />
                <span asp-validation-for="Full_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stance" class="control-label"></label>
                <input asp-for="Stance" class="form-control" />
                <span asp-validation-for="Stance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p></p>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FavouriteBoxers/Views/Boxer/Index.cshtml
@model IEnumerable<FavouriteBoxers.Models.Boxer>

@{
    ViewData["Title"] = "Index";
}

<h1>Boxers</h1>

<p>
    <a asp-action="Create">Add another boxer</a> <a>&nbsp</a> <a asp-action="ShowSearchForm">Search</a>

</p>
@{
    if (Model.Count() == 0)
    {
        <p>No such boxer</p>

    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Full_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alias)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nationality)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Stance)
                    </th>
                    <th>
                        Age
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DOB)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Full_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Alias)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nationality)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stance)
                        </td>
                        <td>
                            @item.setAge(item.DOB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DOB)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}


FavouriteBoxers/Views/Boxer/ShowSearchForm.cshtml
<h4>Search for a boxer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>

FavouriteBoxers/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Favourite Boxers</h1>
    <p>A web application to display my favourite boxers!</p>
</div>

FavouriteBoxers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FavouriteBoxers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FavouriteBoxers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FavouriteBoxers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boxer" asp-action="Index">Boxers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boxer" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FavouriteBoxers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>